### ISSUE TITLE
Не работают ссылки "Клавостатистика", "История игрока", "Созданные словари"

### ISSUE THREAD

**Issue by P-h-e-m-m-e-r** [Fenex/klavotools-kango#18]
Не работают ссылки "Клавостатистика", "История игрока", "Созданные словари" в профиле

**Comment by filippovdaniil** [comment]
Уже разобрались — проблема связана с пользовательским скриптом [klavostat_links](https://github.com/voidmain02/KgScripts/blob/master/docs/klavostats_links.md).
