### ISSUE TITLE
Постоянное «присутствие» на сайте

### ISSUE THREAD

**Issue by filippovdaniil** [Fenex/klavotools-kango#21]
Запросы на список текущих соревнований, сделанные при помощи метода `kango.xhr.send()` всегда уходят с cookies, что приводит к вечному онлайну на сайте. Можно использовать глобальный метод [fetch](https://developer.mozilla.org/en-US/docs/Web/API/GlobalFetch) (если он доступен), который по умолчанию не отправляет cookies.

**Comment by Fenex** [comment]
Не прошло тесты. =(

**Comment by filippovdaniil** [comment]
Да, они поломались из-за промисов. Для них тесты нужно писать немного по-другому + тут еще, похоже, фейл с фейковыми таймерами sinon.js произошел. В старой ноде, с которой прогоняются тесты в Travis, нет «нативных» промисов, поэтому Q использует фоллбек на таймерах, которые, в свою очередь, просто «замораживаются» и не работают.

Я тут тоже со вчерашнего дня сидел с этой issue, но в результате вообще решил отказаться от таких запросов по таймеру, и использовать уже реализованное соединение на WebSocket: #22 (основные тесты пофиксил, но нужно будет еще дописать для трех методов).
