### ISSUE TITLE
Оповещения о рейтинговых соревнованиях

### ISSUE THREAD

**Issue by filippovdaniil** [Fenex/klavotools-kango#3]
![notification](https://cloud.githubusercontent.com/assets/154306/6866644/af3b658c-d4a4-11e4-82c4-8b9347c27bb4.png)

Думаю, для этих уведомлений о рейтинговых соревнованиях имеет смысл использовать [Web Notification API](https://developer.mozilla.org/en-US/docs/Web/API/notification) — они отображаются на уровне системы, т.е. будут появляться даже если окно браузера свернуто.

**Comment by Fenex** [comment]
Пулл-реквест #5, закрыто.
