### ISSUE TITLE
Закончить заезд по количеству ошибок.

### ISSUE THREAD

**Issue by dotru** [Fenex/klavotools-kango#32]
Не пойму куда настройка делась? Раньше можно было ограничить количество ошибок в заезде.

**Comment by filippovdaniil** [comment]
Эта настройка была реализована пользовательским скриптом [control_error_mode](https://github.com/voidmain02/KgScripts/blob/master/scripts/control_error_mode.user.js), который перестал работать после недавних изменений в коде клавогонок (равно как перестали работать и [многие другие](https://github.com/voidmain02/KgScripts/issues/91#issuecomment-263502130) скрипты). К сожалению, в ближайшее время его вряд ли кто-нибудь исправит.
