### ISSUE TITLE
Обновление для chromium

### ISSUE THREAD

**Issue by scarpion908** [Fenex/klavotools-kango#40]
Решил пока начать смотреть, что работает и нет в новой версии.
Собственно проверял в Linux с chrome 79.
Под виндой потом тоже надо будет глянуть как время будет.

По поводу установки самого дополнения.
Я так понимаю, что сейчас его установить в chrome можно только либо из магазина (но этот вариант отпадает для проверки новой версии), либо включив developer mode и залив распакованным. Собственно этим и пользовался. Более того, для хрома теперь вроде как требуется 3-й формат crx, который генерировать посложнее, чем 2-й. Есть скрипты для npm или на python, которые должны это делать. Ну или просто самим хром через консоль или через chrome:extension, указав путь до распакованного и и pem файл. Однако что потом с полученным crx файлом 3-й версии делать, я все равно не понял, т.к. залить куда-либо руками его не нашел возможности. В связи с этим можно подправить dodo.py, чтобы генерил в build  xpi для firefox и распакованный вариант. Можно еще генерить, конечно, crx3, но получается, что он бесполезен для всех, кроме автора приложения в магазине.

По поводу уведомлений.
Уведомления на события работали в Linux - потом еще на win10 гляну.
Однако приглашения от друзей почему-то не видел. Специально включил галку в настройках сайта, тогда стал видеть приглашения через базовый интерфейс, но не через KTS. На firefox работают.

По поводу контекстного меню в popup.
Редиректы по Left, Middle - работают. Right - не работает. Вместо него всегда вылезает контекстное меню с пунктом "Inspect". Пишут, что это нормально при включенном developer mode. Однако у меня при выключенном devmode для старой версии дополнения и для других дополнений это тоже вылезало. В общем не знаю, можно ли с этим что-то сделать. Может быть, проще вообще не использовать Right click event здесь?

По поводу скриптов в KgScripts.
Я так понимаю, что ты их обновишь сам, как время будет?
В целом, с тем вариантом из PR я поездил некоторое время, особо багов обнаружено не было. carmero вроде как тоже их посмотрел. Но можно будет еще некоторые отдельно глянуть с новым KTS.

По поводу принудительного редиректа на http для TS.
Идея в целом понятная, т.к. сомневаюсь что для TS появится https, особенно при отсутствии сорцов. Да и в целом с учетом нестабильной его работы порой SSL там явно может добавить серьезных проблем без должной отладки.
Однако есть вариант еще один. Некоторые раньше заходили через https и логинились (ну или регались) и дальше уже переключались на http. Сейчас получится что принудительный редирект (он же вроде как включен по умолчанию) будет всегда их выкидывать на http, даже при попытке залогиниться.

Если еще что-нибудь найдется, тогда отпишу сюда же.

**Comment by Fenex** [comment]
По поводу Chrome ничего не подскажу, надо изучать этот вопрос. При выпуске КТС 3.6.0 я понял что исследование отнимет много времени и это единственная причина, по которой я не стал публиковать обновление для хромиумов.

> ... В связи с этим можно подправить dodo.py, чтобы генерил в build xpi для firefox и распакованный вариант.

На сколько я помню, в процессе сборки происходит копирование необходимых файлов во временную папку, т.е. директория с распакованным расширением уже существует. Надо сменить место назначения с временной директории на путь внутри репозитория (и добавить путь в .gitignore если требуется).

> По поводу контекстного меню в popup.
> Редиректы по Left, Middle - работают. Right - не работает. Вместо него всегда вылезает контекстное меню с пунктом "Inspect". Пишут, что это нормально при включенном developer mode. Однако у меня при выключенном devmode для старой версии дополнения и для других дополнений это тоже вылезало. В общем не знаю, можно ли с этим что-то сделать. Может быть, проще вообще не использовать Right click event здесь?

Если нет возможности убрать контекстное меню, то да, возможно стоит отказаться от ПКМ совсем. Изначально я делал три режима открытия без ПКМ: открытие в новой активной вкладке выполнялось при двойном щелчке. Изменено коммитом 59a6b02bc4e09a9bda18ef65a0152f061f7a47fb (почему - не знаю, надо спрашивать у автора коммита, но с учётом прошедшего времени - не думаю, что ситуация прояснится).

> По поводу скриптов в KgScripts.
> Я так понимаю, что ты их обновишь сам, как время будет?
> В целом, с тем вариантом из PR я поездил некоторое время, особо багов обнаружено не было. carmero вроде как тоже их посмотрел. Но можно будет еще некоторые отдельно глянуть с новым KTS.

Да, обновлю. Я забрал коммиты из PR voidmain02/KgScripts/pull/109 и обновил версии. Ещё планирую прикрутить Github Actions для проверки соответствия выставленных версий в `klavotools.json` и в meta данных скриптов. Скоро уже будет в доступе.

> По поводу принудительного редиректа на http для TS.

С TS всё сложно, хотя в теории решаемо (как мне кажется на данный момент). Но опять же, требуется время на исследования.

> Однако есть вариант еще один. Некоторые раньше заходили через https и логинились (ну или регались) и дальше уже переключались на http. Сейчас получится что принудительный редирект (он же вроде как включен по умолчанию) будет всегда их выкидывать на http, даже при попытке залогиниться.

Решение в лоб: страницу `/login/` грузить только по `https` протоколу, а при нажатии кнопки "Вход" делать редирект на `/login/` вместо отображения popup-окна.

**Comment by scarpion908** [comment]
И итоге что получилось:
1. По поводу сборки - отдельный PR #42 сделан с добавлением отдельной директории unpacked в build. Годится только для тестирования. Для нормального распространения в chrome нужна публикация в магазине.
2. По поводу уведомлений о приглашениях от друзей. Баг исправлен в PR #41 и оказался не связан с chrome. Есть некоторые мысли, что еще можно поменять с уведомлениями, но это если будет свободное время/желание этим заняться и в отдельный issue.
3. По поводу контекстного меню в popup. Коммит https://github.com/Fenex/klavotools-kango/commit/59a6b02bc4e09a9bda18ef65a0152f061f7a47fb видимо связан с https://klavogonki.ru/forum/software/12/page50/#post1021 который изначально появился после пожелания `А вот когда ищешь ник в клавотулсе и переходишь по нему, он всегда открывает в том же окне, что вообще неудобно, особенно когда в иксе сидишь ищешь. Тут надо сделать в новом окне.` Тут в целом согласен, и, возможно, стоит использовать решение от agile, когда по ЛКМ - это открытие новой вкладки и переход в нее, по средней кнопке - открытие в бекграунде. Правую - не использовать, если не будет возможности использовать ее во всех браузерах. Ну или вообще вынести возможность выбора действия в настройки, но это опять при наличии времени/желания и т.д. и в отдельный issue/PR.
4. По поводу логина получается, что либо (как предложено) вообще убрать возможность вводить их при подключении по http. Либо в KTS городить какие-то проверки и не делать принудительный редирект на http, если пользователь не залогинен. Хотя тут более оптимальным вариантом кажется первый.

Этот issue оставлю пока, пусть дальше висит. Может еще что-нибудь связанное с chrome вылезет, или в магазин проверку не пройдет, к примеру.

**Comment by Fenex** [comment]
> Этот issue оставлю пока, пусть дальше висит. Может еще что-нибудь связанное с chrome вылезет, или в магазин проверку не пройдет, к примеру.
Опубликовано в webstore, это успех.

**Comment by scarpion908** [comment]
Раз в магазин добавили, то можно закрыть.
Если будут баги какие-нибудь, то в отдельные лучше выносить.
