### ISSUE TITLE
Пропадает фон (green-back) в шапке страницы у залогиненных юзеров

### ISSUE THREAD

**Issue by scarpion908** [Fenex/klavotools-kango#44]
Собственно проблема не связана с KTS, а скорее с самим сайтом.

1. Удаляем KTS и разлогиниваемся с клавогонок (для надежности еще кеш почистил)
2. Заходим как гость - [видим](https://ibb.co/YXqJnTP), что зеленый фон на месте.
Inspect: 	`<div id="head" class="minwidth green-back">`
3. Логинимся и [видим](https://ibb.co/0ZHnXFq), что зеленый фон пропал.
Inspect: `<div id="head" class="minwidth ">`
4. Руками добавляем green-back - фон [вернулся](https://ibb.co/J7PWmtb).

Полагаю, что отлетело после какого-нибудь апдейта.
Из-за этого же не работает подсветка стилей KTS в данном месте.

**Comment by Fenex** [comment]
Вообще говоря, если у пользователя есть аккаунт премиум, то зелёное поле с самолётом и рекламным блоком не выводится. А следовательно зелёный градиент в этом случае выводить не предполагалось. Поэтому класс `green-back` не выставляется, это всегда так работало.

**Comment by scarpion908** [comment]
Понял.
Ладно, раз так и было, то пусть дальше остается.
