### ISSUE TITLE
Когда включена KlavoTools письмо для восстановление не срабатывают.

### ISSUE THREAD

**Issue by Akmatworld** [Fenex/klavotools-kango#45]
Несколько дней назад я столкнулся с проблемой, тогда я не смог восстановить свой пароль от клавогонки, тогда я не знал что делать, не нашел проблему, почему так.
После пару часов я попробовал восстановить через Firefox(чистый без никаких расширений), я смог восстановить свой пароль.  

Сегодня я решил выяснить почему так происходит.
Я по одному попробовал отключить сторонние расширение в Google Chrome и проверить восстановление.
Когда я дошел до KlavoTools отключив его я успешно восстановил свой пароль.
Думал это какая-то ошибка и попробовал в другом браузере Firefox, перед тем как начать восстановление я установил расширение KlavoTools в Firefox.
И начал тестить в первом же попытке я получил аналогичную проблему как у Google Chrome.
Несколько раз попробовал не сработала. А потом отключил расширение KlavoTools в Firefox, после отключение сразу же восстановление было успешно.
@Fenex

**Comment by Fenex** [comment]
Похоже, что такое поведение возможно если в настройках КТС выставлено 
принудительное переключение на иной протокол. Для запрета перезагрузки 
страницы надо внести URL-адрес сброса пароля с GET-параметром `key` в 
чёрный список.

`/remind/?key=`


04.05.2020 14:58, SA пишет:
>
> Несколько дней назад я столкнулся с проблемой, тогда я не смог 
> восстановить свой пароль от клавогонки, тогда я не знал что делать, не 
> нашел проблему, почему так.
> После пару часов я попробовал восстановить через Firefox(чистый без 
> никаких расширений), я смог восстановить свой пароль.
>
> Сегодня я решил выяснить почему так происходит.
> Я по одному попробовал отключить сторонние расширение в Google Chrome 
> и проверить восстановление.
> Когда я дошел до KlavoTools отключив его я успешно восстановил свой 
> пароль.
> Думал это какая-то ошибка и попробовал в другом браузере Firefox, 
> перед тем как начать восстановление я установил расширение KlavoTools 
> в Firefox.
> И начал тестить в первом же попытке я получил аналогичную проблему как 
> у Google Chrome.
> Несколько раз попробовал не сработала. А потом отключил расширение 
> KlavoTools в Firefox, после отключение сразу же восстановление было 
> успешно.
>
